# Rustfmt Configuration for Butabuti
#
# This file defines code formatting standards for the Butabuti embroidery library.
# Run `cargo fmt` to apply these settings automatically.

# Stable features (supported in stable Rust)
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments and documentation
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Strings
format_strings = true

# Function calls and definitions
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
match_arm_trailing_comma = true

# Whitespace
use_field_init_shorthand = true
use_try_shorthand = true
remove_nested_parens = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false

# Blank lines
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1

# Item visibility
reorder_impl_items = true

# Struct fields
struct_field_align_threshold = 0

# Error handling
error_on_line_overflow = false
error_on_unformatted = false

# Miscellaneous
overflow_delimited_expr = true
condense_wildcard_suffixes = true
force_explicit_abi = true
