# Rustfmt configuration for Butabuti
# https://rust-lang.github.io/rustfmt/
# Only using stable features (no nightly-only options)

# Rust edition
edition = "2021"

# Maximum line width
max_width = 100

# Use small heuristics for breaking long items
use_small_heuristics = "Default"

# Reorder imports alphabetically
reorder_imports = true

# Reorder modules alphabetically
reorder_modules = true

# Use field init shorthand (e.g., `Point { x, y }` instead of `Point { x: x, y: y }`)
use_field_init_shorthand = true

# Use try shorthand (`?` instead of `try!()`)
use_try_shorthand = true

# Newline style (Unix = LF)
newline_style = "Unix"

# Match block trailing comma
match_block_trailing_comma = true

# Remove nested parentheses when possible
remove_nested_parens = true

# Hard tabs for indentation
hard_tabs = false

# Tab spaces (when hard_tabs = false)
tab_spaces = 4
