name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the following information to help us diagnose and fix the issue.

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version of Butabuti
          required: true
        - label: I have read the [FAQ](https://github.com/Fahad090NP/butabuti/wiki/FAQ) and [documentation](https://docs.rs/butabuti)
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Example: Pattern loses color information when converting from DST to PES"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Load pattern from 'example.dst'
        2. Convert to PES format
        3. Re-read PES file
        4. Observe missing color information
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "Colors should be preserved during format conversion"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "All stitches converted to black"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (data loss, crashes, security)
        - High (major functionality broken)
        - Medium (feature partially works)
        - Low (minor issue, workaround available)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Butabuti Version
      description: What version of Butabuti are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.70.0 (90c541806 2023-05-31)"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows
        - macOS
        - Linux
        - WASM/Browser
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: Affected Format(s)
      description: Which embroidery format is affected? (Select all that apply)
      multiple: true
      options:
        - DST
        - PES
        - JEF
        - VP3
        - EXP
        - SEW
        - XXX
        - HUS
        - VIP
        - BRO
        - U01
        - DAT
        - "100"
        - 10O
        - DSB
        - SVG
        - PNG
        - TXT
        - Not format-specific
        - Unknown
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code to reproduce the issue
      render: rust
      placeholder: |
        use butabuti::prelude::*;

        fn main() -> Result<()> {
            let mut pattern = EmbPattern::new();
            // Your code here
            Ok(())
        }
    validations:
      required: false

  - type: textarea
    id: files
    attributes:
      label: Sample Files
      description: If possible, attach or link to files that demonstrate the issue
      placeholder: |
        Attach files by dragging and dropping, selecting, or pasting them.
        If files are large or proprietary, describe them instead.
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: Error Messages / Stack Trace
      description: Full error output if applicable
      render: shell
      placeholder: |
        Error: Parse error: Invalid header size: expected 512, got 256
            at src/formats/io/readers/dst.rs:45
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - This only happens with files from a specific embroidery machine
        - Works fine with version 0.0.9
        - Related to issue #123
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this issue?
      options:
        - label: I am willing to submit a pull request to fix this bug
          required: false
        - label: I can provide more test files if needed
          required: false
