//! Janome JEF thread color palette
//!
//! Contains 79 predefined thread colors used in JEF embroidery files,
//! with RGB values and catalog numbers for Janome embroidery machines.

use crate::core::thread::EmbThread;
use lazy_static::lazy_static;

lazy_static! {
    /// Janome JEF thread palette (79 colors)
    pub static ref JEF_THREADS: Vec<Option<EmbThread>> = vec![
        None, // Placeholder
        Some(EmbThread::new(0x000000).with_description("Black").with_catalog_number("002").with_brand("Janome")),
        Some(EmbThread::new(0xFFFFFF).with_description("White").with_catalog_number("001").with_brand("Janome")),
        Some(EmbThread::new(0xFFFF17).with_description("Yellow").with_catalog_number("204").with_brand("Janome")),
        Some(EmbThread::new(0xFF6600).with_description("Orange").with_catalog_number("203").with_brand("Janome")),
        Some(EmbThread::new(0x2F5933).with_description("Olive Green").with_catalog_number("219").with_brand("Janome")),
        Some(EmbThread::new(0x237336).with_description("Green").with_catalog_number("226").with_brand("Janome")),
        Some(EmbThread::new(0x65C2C8).with_description("Sky").with_catalog_number("217").with_brand("Janome")),
        Some(EmbThread::new(0xAB5A96).with_description("Purple").with_catalog_number("208").with_brand("Janome")),
        Some(EmbThread::new(0xF669A0).with_description("Pink").with_catalog_number("201").with_brand("Janome")),
        Some(EmbThread::new(0xFF0000).with_description("Red").with_catalog_number("225").with_brand("Janome")),
        Some(EmbThread::new(0xB1704E).with_description("Brown").with_catalog_number("214").with_brand("Janome")),
        Some(EmbThread::new(0x0B2F84).with_description("Blue").with_catalog_number("207").with_brand("Janome")),
        Some(EmbThread::new(0xE4C35D).with_description("Gold").with_catalog_number("003").with_brand("Janome")),
        Some(EmbThread::new(0x481A05).with_description("Dark Brown").with_catalog_number("205").with_brand("Janome")),
        Some(EmbThread::new(0xAC9CC7).with_description("Pale Violet").with_catalog_number("209").with_brand("Janome")),
        Some(EmbThread::new(0xFCF294).with_description("Pale Yellow").with_catalog_number("210").with_brand("Janome")),
        Some(EmbThread::new(0xF999B7).with_description("Pale Pink").with_catalog_number("211").with_brand("Janome")),
        Some(EmbThread::new(0xFAB381).with_description("Peach").with_catalog_number("212").with_brand("Janome")),
        Some(EmbThread::new(0xC9A480).with_description("Beige").with_catalog_number("213").with_brand("Janome")),
        Some(EmbThread::new(0x970533).with_description("Wine Red").with_catalog_number("215").with_brand("Janome")),
        Some(EmbThread::new(0xA0B8CC).with_description("Pale Sky").with_catalog_number("216").with_brand("Janome")),
        Some(EmbThread::new(0x7FC21C).with_description("Yellow Green").with_catalog_number("218").with_brand("Janome")),
        Some(EmbThread::new(0xE5E5E5).with_description("Silver Gray").with_catalog_number("220").with_brand("Janome")),
        Some(EmbThread::new(0x889B9B).with_description("Gray").with_catalog_number("221").with_brand("Janome")),
        Some(EmbThread::new(0x98D6BD).with_description("Pale Aqua").with_catalog_number("227").with_brand("Janome")),
        Some(EmbThread::new(0xB2E1E3).with_description("Baby Blue").with_catalog_number("228").with_brand("Janome")),
        Some(EmbThread::new(0x368BA0).with_description("Powder Blue").with_catalog_number("229").with_brand("Janome")),
        Some(EmbThread::new(0x4F83AB).with_description("Bright Blue").with_catalog_number("230").with_brand("Janome")),
        Some(EmbThread::new(0x386A91).with_description("Slate Blue").with_catalog_number("231").with_brand("Janome")),
        Some(EmbThread::new(0x071650).with_description("Navy Blue").with_catalog_number("232").with_brand("Janome")),
        Some(EmbThread::new(0xF999A2).with_description("Salmon Pink").with_catalog_number("233").with_brand("Janome")),
        Some(EmbThread::new(0xF9676B).with_description("Coral").with_catalog_number("234").with_brand("Janome")),
        Some(EmbThread::new(0xE3311F).with_description("Burnt Orange").with_catalog_number("235").with_brand("Janome")),
        Some(EmbThread::new(0xE2A188).with_description("Cinnamon").with_catalog_number("236").with_brand("Janome")),
        Some(EmbThread::new(0xB59474).with_description("Umber").with_catalog_number("237").with_brand("Janome")),
        Some(EmbThread::new(0xE4CF99).with_description("Blond").with_catalog_number("238").with_brand("Janome")),
        Some(EmbThread::new(0xFFCB00).with_description("Sunflower").with_catalog_number("239").with_brand("Janome")),
        Some(EmbThread::new(0xE1ADD4).with_description("Orchid Pink").with_catalog_number("240").with_brand("Janome")),
        Some(EmbThread::new(0xC3007E).with_description("Peony Purple").with_catalog_number("241").with_brand("Janome")),
        Some(EmbThread::new(0x80004B).with_description("Burgundy").with_catalog_number("242").with_brand("Janome")),
        Some(EmbThread::new(0x540571).with_description("Royal Purple").with_catalog_number("243").with_brand("Janome")),
        Some(EmbThread::new(0xB10525).with_description("Cardinal Red").with_catalog_number("244").with_brand("Janome")),
        Some(EmbThread::new(0xCAE0C0).with_description("Opal Green").with_catalog_number("245").with_brand("Janome")),
        Some(EmbThread::new(0x899856).with_description("Moss Green").with_catalog_number("246").with_brand("Janome")),
        Some(EmbThread::new(0x5C941A).with_description("Meadow Green").with_catalog_number("247").with_brand("Janome")),
        Some(EmbThread::new(0x003114).with_description("Dark Green").with_catalog_number("248").with_brand("Janome")),
        Some(EmbThread::new(0x5DAE94).with_description("Aquamarine").with_catalog_number("249").with_brand("Janome")),
        Some(EmbThread::new(0x4CBF8F).with_description("Emerald Green").with_catalog_number("250").with_brand("Janome")),
        Some(EmbThread::new(0x007772).with_description("Peacock Green").with_catalog_number("251").with_brand("Janome")),
        Some(EmbThread::new(0x595B61).with_description("Dark Gray").with_catalog_number("252").with_brand("Janome")),
        Some(EmbThread::new(0xFFFFF2).with_description("Ivory White").with_catalog_number("253").with_brand("Janome")),
        Some(EmbThread::new(0xB15818).with_description("Hazel").with_catalog_number("254").with_brand("Janome")),
        Some(EmbThread::new(0xCB8A07).with_description("Toast").with_catalog_number("255").with_brand("Janome")),
        Some(EmbThread::new(0x986C80).with_description("Salmon").with_catalog_number("256").with_brand("Janome")),
        Some(EmbThread::new(0x98692D).with_description("Cocoa Brown").with_catalog_number("257").with_brand("Janome")),
        Some(EmbThread::new(0x4D3419).with_description("Sienna").with_catalog_number("258").with_brand("Janome")),
        Some(EmbThread::new(0x4C330B).with_description("Sepia").with_catalog_number("259").with_brand("Janome")),
        Some(EmbThread::new(0x33200A).with_description("Dark Sepia").with_catalog_number("260").with_brand("Janome")),
        Some(EmbThread::new(0x523A97).with_description("Violet Blue").with_catalog_number("261").with_brand("Janome")),
        Some(EmbThread::new(0x0D217E).with_description("Blue Ink").with_catalog_number("262").with_brand("Janome")),
        Some(EmbThread::new(0x1E77AC).with_description("Sola Blue").with_catalog_number("263").with_brand("Janome")),
        Some(EmbThread::new(0xB2DD53).with_description("Green Dust").with_catalog_number("264").with_brand("Janome")),
        Some(EmbThread::new(0xF33689).with_description("Crimson").with_catalog_number("265").with_brand("Janome")),
        Some(EmbThread::new(0xDE649E).with_description("Floral Pink").with_catalog_number("266").with_brand("Janome")),
        Some(EmbThread::new(0x984161).with_description("Wine").with_catalog_number("267").with_brand("Janome")),
        Some(EmbThread::new(0x4C5612).with_description("Olive Drab").with_catalog_number("268").with_brand("Janome")),
        Some(EmbThread::new(0x4C881F).with_description("Meadow").with_catalog_number("269").with_brand("Janome")),
        Some(EmbThread::new(0xE4DE79).with_description("Mustard").with_catalog_number("270").with_brand("Janome")),
        Some(EmbThread::new(0xCB8A1A).with_description("Yellow Ocher").with_catalog_number("271").with_brand("Janome")),
        Some(EmbThread::new(0xCBA21C).with_description("Old Gold").with_catalog_number("272").with_brand("Janome")),
        Some(EmbThread::new(0xFF9805).with_description("Honey Dew").with_catalog_number("273").with_brand("Janome")),
        Some(EmbThread::new(0xFCB257).with_description("Tangerine").with_catalog_number("274").with_brand("Janome")),
        Some(EmbThread::new(0xFFE505).with_description("Canary Yellow").with_catalog_number("275").with_brand("Janome")),
        Some(EmbThread::new(0xF0331F).with_description("Vermilion").with_catalog_number("202").with_brand("Janome")),
        Some(EmbThread::new(0x1A842D).with_description("Bright Green").with_catalog_number("206").with_brand("Janome")),
        Some(EmbThread::new(0x386CAE).with_description("Ocean Blue").with_catalog_number("222").with_brand("Janome")),
        Some(EmbThread::new(0xE3C4B4).with_description("Beige Gray").with_catalog_number("223").with_brand("Janome")),
        Some(EmbThread::new(0xE3AC81).with_description("Bamboo").with_catalog_number("224").with_brand("Janome")),
    ];
}
