//! Brother PEC thread color palette
//!
//! Contains 64 predefined thread colors used in PEC embroidery files,
//! with RGB values for Brother embroidery machines and cards.

use crate::core::thread::EmbThread;
use lazy_static::lazy_static;

lazy_static! {
    /// Brother PEC thread palette (64 colors)
    pub static ref PEC_THREADS: Vec<EmbThread> = vec![
        EmbThread::new(0x000000).with_description("Unknown").with_brand("Brother"),
        EmbThread::new(0x1A1A1A).with_description("Prussian Blue").with_brand("Brother"),
        EmbThread::new(0x0F75FF).with_description("Blue").with_brand("Brother"),
        EmbThread::new(0x00934C).with_description("Teal Green").with_brand("Brother"),
        EmbThread::new(0xBA732C).with_description("Corn Flower Blue").with_brand("Brother"),
        EmbThread::new(0xFF0000).with_description("Red").with_brand("Brother"),
        EmbThread::new(0xFD6C2C).with_description("Reddish Brown").with_brand("Brother"),
        EmbThread::new(0xFE86CD).with_description("Magenta").with_brand("Brother"),
        EmbThread::new(0xFECEDD).with_description("Light Lilac").with_brand("Brother"),
        EmbThread::new(0xCF68D7).with_description("Lilac").with_brand("Brother"),
        EmbThread::new(0x9741FF).with_description("Mint Green").with_brand("Brother"),
        EmbThread::new(0x3FFF54).with_description("Deep Gold").with_brand("Brother"),
        EmbThread::new(0xFFB900).with_description("Orange").with_brand("Brother"),
        EmbThread::new(0xFFE600).with_description("Yellow").with_brand("Brother"),
        EmbThread::new(0xC3FF4B).with_description("Lime Green").with_brand("Brother"),
        EmbThread::new(0x7FC21C).with_description("Brass").with_brand("Brother"),
        EmbThread::new(0xDBFFA9).with_description("Silver").with_brand("Brother"),
        EmbThread::new(0xFFE5CE).with_description("Russet Brown").with_brand("Brother"),
        EmbThread::new(0xFFA7B4).with_description("Cream Brown").with_brand("Brother"),
        EmbThread::new(0xFFA2D8).with_description("Pewter").with_brand("Brother"),
        EmbThread::new(0x000000).with_description("Black").with_brand("Brother"),
        EmbThread::new(0xA6FFFF).with_description("Ultramarine").with_brand("Brother"),
        EmbThread::new(0x0066FF).with_description("Royal Blue").with_brand("Brother"),
        EmbThread::new(0xCCCCFF).with_description("Dark Gray").with_brand("Brother"),
        EmbThread::new(0xCC99BA).with_description("Dark Brown").with_brand("Brother"),
        EmbThread::new(0xFF3300).with_description("Deep Rose").with_brand("Brother"),
        EmbThread::new(0xFF6D42).with_description("Light Brown").with_brand("Brother"),
        EmbThread::new(0xFF00CC).with_description("Salmon Pink").with_brand("Brother"),
        EmbThread::new(0xFFCCE6).with_description("Vermillion").with_brand("Brother"),
        EmbThread::new(0xFFFFFF).with_description("White").with_brand("Brother"),
        EmbThread::new(0x8FCFDC).with_description("Violet").with_brand("Brother"),
        EmbThread::new(0xC89CFF).with_description("Seacrest").with_brand("Brother"),
        EmbThread::new(0x7FC7DB).with_description("Sky Blue").with_brand("Brother"),
        EmbThread::new(0xFFFF99).with_description("Pumpkin").with_brand("Brother"),
        EmbThread::new(0xFFFB74).with_description("Cream Yellow").with_brand("Brother"),
        EmbThread::new(0x00CF35).with_description("Khaki").with_brand("Brother"),
        EmbThread::new(0xF9BA82).with_description("Clay Brown").with_brand("Brother"),
        EmbThread::new(0xFFCC00).with_description("Leaf Green").with_brand("Brother"),
        EmbThread::new(0xD6FFFF).with_description("Peacock Blue").with_brand("Brother"),
        EmbThread::new(0xC08EDE).with_description("Gray").with_brand("Brother"),
        EmbThread::new(0xF49BFF).with_description("Warm Gray").with_brand("Brother"),
        EmbThread::new(0x280091).with_description("Dark Purple").with_brand("Brother"),
        EmbThread::new(0xFF6600).with_description("Flesh Pink").with_brand("Brother"),
        EmbThread::new(0xFF9999).with_description("Pink").with_brand("Brother"),
        EmbThread::new(0xDC0073).with_description("Deep Green").with_brand("Brother"),
        EmbThread::new(0x00AA00).with_description("Lavender").with_brand("Brother"),
        EmbThread::new(0xE1E1E1).with_description("Wisteria Violet").with_brand("Brother"),
        EmbThread::new(0xFFFFC1).with_description("Beige").with_brand("Brother"),
        EmbThread::new(0xFFE38C).with_description("Carmine").with_brand("Brother"),
        EmbThread::new(0xFF9EC0).with_description("Amber Red").with_brand("Brother"),
        EmbThread::new(0x7FC21C).with_description("Olive Green").with_brand("Brother"),
        EmbThread::new(0x90EE90).with_description("Dark Fuchsia").with_brand("Brother"),
        EmbThread::new(0xFF99FF).with_description("Tangerine").with_brand("Brother"),
        EmbThread::new(0xFFCC99).with_description("Light Blue").with_brand("Brother"),
        EmbThread::new(0xFFE6F1).with_description("Emerald Green").with_brand("Brother"),
        EmbThread::new(0xAC7399).with_description("Purple").with_brand("Brother"),
        EmbThread::new(0x99CCFF).with_description("Moss Green").with_brand("Brother"),
        EmbThread::new(0xFFE3E3).with_description("Flesh Pink").with_brand("Brother"),
        EmbThread::new(0xFFCCF0).with_description("Harvest Gold").with_brand("Brother"),
        EmbThread::new(0xFF9999).with_description("Electric Blue").with_brand("Brother"),
        EmbThread::new(0xFFDB1E).with_description("Lemon Yellow").with_brand("Brother"),
        EmbThread::new(0xFFF870).with_description("Fresh Green").with_brand("Brother"),
        EmbThread::new(0xF39178).with_description("Applique Material").with_brand("Brother"),
        EmbThread::new(0xFFFFDC).with_description("Applique Position").with_brand("Brother"),
    ];
}
